name: Build

on: [push, pull_request]

jobs:

  source-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Install build dependencies
        run: |
          sudo apt install -y ronn
      - name: Install perl test dependencies
        uses: perl-actions/install-with-cpanm@v1.4
        with:
          install: |
            Shell::Command
            Test::Most
      - name: Configure
        run: |
          ./bootstrap.sh
          ./configure --enable-developer-mode
      - name: Run tests
        run: |
          make check
      - name: Build source package
        run: |
          make dist
          echo VERSION=$(cat .version) >> $GITHUB_ENV
      - name: Post build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vcsh-${{ env.VERSION }}
          path: vcsh-${{ env.VERSION }}.zip

  standalone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Configure standalone script
        run: |
          ./bootstrap.sh
          ./configure --with-standalone --bindir=/
          make DESTDIR=. install-exec
          echo VERSION=$(cat .version) >> $GITHUB_ENV
          sha256sum vcsh-standalone.sh
      - name: Post standalone script artifact
        uses: actions/upload-artifact@v4
        with:
          name: standalone-deployment-${{ env.VERSION }}
          path: vcsh-standalone.sh
