name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:

  standalone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure standalone script
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          ./bootstrap.sh
          ./configure \
              --without-man-page \
              --disable-tests \
              --without-bash-completion-dir \
              --without-zsh-completion-dir \
              --with-deployment=standalone \
              COMM=comm GIT=git GREP=grep SED=sed SHELL=/bin/sh
      - name: Upload standalone script artifact
        uses: actions/upload-artifact@v2
        with:
          name: vcsh-standalone
          path: vcsh

  ghrelase:
    runs-on: ubuntu-latest
    needs: [ standalone ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install ronn
        run: |
          sudo apt update
          sudo apt install -y ronn
      - name: Configure
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo "${GITHUB_REF#refs/*/v}" > .tarball-version
          ./bootstrap.sh
          ./configure
      - name: Build source package
        run: |
          make dist
      - name: Check source package behaviour
        run: |
          make distcheck
      - name: Make sure changelog was updated
        run: |
          make changelog-HEAD
          grep -F "* Release ${{ env.VERSION }}" changelog-HEAD
      - name: Download standalone script artifact
        uses: actions/download-artifact@v2
        with:
          name: vcsh-standalone
          path: standalone
      - name: Rename standalone deployment script
        run: mv standalone/vcsh vcsh-standalone.sh
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog-HEAD
          files: |
            vcsh-${{ env.VERSION }}.zip
            vcsh-${{ env.VERSION }}.tar.xz
            vcsh-standalone.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
