name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:

  ghrelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt install -y ronn
      - name: Configure
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo "${GITHUB_REF#refs/*/v}" > .tarball-version
          ./bootstrap.sh
          ./configure
      - name: Make sure changelog was updated
        run: |
          make changelog-HEAD
          grep -F "* Release ${{ env.VERSION }}" changelog-HEAD
      - name: Build source package
        run: |
          make dist
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog-HEAD
          files: |
            vcsh-${{ env.VERSION }}.zip
            vcsh-${{ env.VERSION }}.tar.xz
        env:
          GITHUB_TOKEN: ${{ github.token }}

  deploy-standalone:
    runs-on: ubuntu-latest
    needs: [ ghrelease ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure standalone script
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          ./bootstrap.sh
          ./configure --with-standalone --bindir=/
          make DESTDIR=. install-exec
      - name: Add standalone deployment to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: vcsh-standalone.sh
          tag: ${{ github.ref }}
