name: Test

on: [push, pull_request]

jobs:

  standalone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Configure standalone script
        run: |
          ./bootstrap.sh
          ./configure \
              --without-man-page \
              --disable-tests \
              --without-bash-completion-dir \
              --without-zsh-completion-dir \
              --with-deployment=standalone \
              COMM=comm GIT=git GREP=grep SED=sed SHELL=/bin/sh
      - name: Post standalone script artifact
        uses: actions/upload-artifact@v2
        with:
          name: vcsh-standalone
          path: vcsh

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Install dependencies
        run: |
          sudo apt install ronn
      - name: Install perl test dependencies
        uses: perl-actions/install-with-cpanm@v1.1
        with:
          install: |
            Shell::Command
            Test::Most
      - name: Configure
        run: |
          ./bootstrap.sh
          ./configure
      - name: Run tests
        run: |
          make check
      - name: Build source package
        run: |
          make dist
          echo VERSION=$(cat .version) >> $GITHUB_ENV
      - name: Post build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vcsh-${{ env.VERSION }}
          path: vcsh-${{ env.VERSION }}.zip
